# Generated by Django 3.1.5 on 2021-02-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='detections/RGB')),
                ('picture_ndvi', models.ImageField(upload_to='detections/NDVI')),
                ('picture_savi', models.ImageField(upload_to='detections/SAVI')),
                ('picture_evi2', models.ImageField(upload_to='detections/EVI2')),
                ('picture_without', models.ImageField(upload_to='detections/Without')),
                ('water_stress', models.FloatField()),
                ('water_stress_percent', models.FloatField()),
                ('satatus_of_field', models.CharField(choices=[('danger', 'Danger'), ('warning', 'Warning'), ('good', 'Good')], default='good', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note_detection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detections.detection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
