# Generated by Django 3.1.5 on 2021-01-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='picture_merge',
        ),
    ]
